clear @s *[minecraft:custom_data~{map:{item:1b}}]

item replace entity @s hotbar.0 with minecraft:written_book[minecraft:custom_data={map:{item:1b,game_info:1b}},minecraft:tooltip_display={hidden_components:["minecraft:written_book_content"]},minecraft:enchantment_glint_override=false,minecraft:written_book_content={pages:[ \
    [{text:""},{text:"VOID CHAINS\n\n",bold:true},{text:"Void Chains is a unique PvP minigame inspired by KOTH, Spleef, and other game modes.\n\nTwo teams compete in an empty arena with Anchors and Bridges suspended over the void.",color:"dark_gray"}], \
    [{text:""},{text:"A TEAM'S ANCHORS...\n\n",bold:true},{text:"- are generated upon game start.\n\n- act as respawn points for the team.\n\n- can be generated by the team on its Bridges.\n\n- can be claimed by the other team.",color:"dark_gray"}], \
    [{text:""},{text:"A TEAM'S BRIDGES...\n\n",bold:true},{text:"- can be formed from within the team's territory (Anchors and Bridges).\n\n- collapse if they are not connected to any of the team's Anchors.\n\n- override the other team's Bridges.",color:"dark_gray"}], \
    [{text:""},{text:"A TEAM WITHOUT ANCHORS...\n\n",bold:true},{text:"- cannot respawn until an Anchor becomes available.\n\n- loses if none of its players are able to play.",color:"dark_gray"}], \
    [{text:""},{text:"THE POWERUP...\n\n",bold:true},{text:"- appears near the arena center.\n\n- is activated by players holding it.\n\n- gets destroyed if not collected on time.",color:"dark_gray"}], \
    [{text:""},{text:"THE BORDER...\n\n",bold:true},{text:"- begins to shrink after some time.\n\n- kills players and destroys Anchors.\n\n- stops eventually, leaving enough space.",color:"dark_gray"}] \
    ],title:"Game Info",author:Ajj},minecraft:lore=[{text:"Void Chains [1.16.0]",color:"gray",italic:0b}]]

item replace entity @s[tag=map.moderation] hotbar.1 with minecraft:mace[minecraft:custom_data={map:{item:1b,moderation_button:1b}},minecraft:consumable={consume_seconds:2147483647f},minecraft:use_effects={can_sprint:true,speed_multiplier:1f},minecraft:tooltip_display={hidden_components:["minecraft:attribute_modifiers"]},minecraft:item_name=[{text:"Moderation... ",color:"green"},{text:"(Right Click)",color:"gray"}]]

function map:lobby/item/update_team_buttons

item replace entity @s[tag=map.cosmetics] hotbar.7 with minecraft:emerald[minecraft:custom_data={map:{item:1b,cosmetics_button:1b}},minecraft:consumable={consume_seconds:2147483647f},minecraft:use_effects={can_sprint:true,speed_multiplier:1f},minecraft:item_name=[{text:"Cosmetics... ",color:"green"},{text:"(Right Click)",color:"gray"}]]
item replace entity @s hotbar.8 with minecraft:iron_chestplate[minecraft:custom_data={map:{item:1b,kits_button:1b}},minecraft:consumable={consume_seconds:2147483647f},minecraft:use_effects={can_sprint:true,speed_multiplier:1f},minecraft:tooltip_display={hidden_components:["minecraft:attribute_modifiers"]},minecraft:item_name=[{text:"Kits... ",color:"green"},{text:"(Right Click)",color:"gray"}]]

function ajjgui:_reload