clear @s *[minecraft:custom_data~{map:{item:1b}}]

item replace entity @s hotbar.0 with minecraft:written_book[minecraft:custom_data={map:{item:1b,game_info:1b}},minecraft:tooltip_display={hidden_components:["minecraft:written_book_content"]},minecraft:enchantment_glint_override=false,minecraft:written_book_content={pages:[ \
    [{text:""},{text:"VOID CHAINS\n\n",bold:true},{text:"Void Chains is a unique PvP minigame inspired by KOTH, Spleef, and other game modes.\n\nTwo teams compete in an empty arena with Anchors and Bridges suspended over the void.",color:"dark_gray"}], \
    [{text:""},{text:"A TEAM'S ANCHORS...\n\n",bold:true},{text:"- are generated upon game start.\n\n- act as respawn points for the team.\n\n- can be generated by the team on its Bridges.\n\n- can be claimed by the other team.",color:"dark_gray"}], \
    [{text:""},{text:"A TEAM'S BRIDGES...\n\n",bold:true},{text:"- can be formed from within the team's territory (Anchors and Bridges).\n\n- collapse if they are not connected to any of the team's Anchors.\n\n- override the other team's Bridges.",color:"dark_gray"}], \
    [{text:""},{text:"A TEAM WITHOUT ANCHORS...\n\n",bold:true},{text:"- cannot respawn until an Anchor becomes available.\n\n- loses if none of its players are able to play.",color:"dark_gray"}], \
    [{text:""},{text:"THE POWERUP...\n\n",bold:true},{text:"- appears near the arena center.\n\n- is activated by players holding it.\n\n- gets destroyed if not collected on time.",color:"dark_gray"}], \
    [{text:""},{text:"THE BORDER...\n\n",bold:true},{text:"- begins to shrink after some time.\n\n- kills players and destroys Anchors.\n\n- stops eventually, leaving enough space.",color:"dark_gray"}] \
    ],title:"Game Info",author:Ajj},minecraft:lore=[{text:"Void Chains [m1.21.9v1]",color:"gray",italic:0b}]]

function map:lobby/item/update_team_buttons

item replace entity @s hotbar.8 with minecraft:compass[minecraft:custom_data={map:{item:1b,player_settings:1b}},minecraft:consumable={consume_seconds:2147483647},minecraft:custom_name=[{text:"Your Settings",color:"green",italic:0b},{text:" (Right Click)",color:"gray"}]]

function ajjgui:_reload